import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const toolDirectory = path.dirname(fileURLToPath(import.meta.url));
const repositoryRoot = path.resolve(toolDirectory, "../../..");
const releasePath = path.join(toolDirectory, "design-release.json");
const sourcePath = path.join(toolDirectory, "code.js");
const tokenPath = path.join(repositoryRoot, "src/styles/tokens.css");
const assetPaths = {
  hero: path.join(repositoryRoot, "src/assets/images/abilene-hero-v2.png"),
  about: path.join(repositoryRoot, "src/assets/images/abilene-about-v2.png"),
};
const vectorPaths = {
  favicon: path.join(repositoryRoot, "public/favicon.svg"),
  brandMark: path.join(repositoryRoot, "src/assets/brand/abilene-mark.svg"),
};
const outputDirectory = path.join(toolDirectory, "dist");
const outputPath = path.join(outputDirectory, "code.js");

const release = JSON.parse(fs.readFileSync(releasePath, "utf8"));
const source = fs.readFileSync(sourcePath, "utf8");
const tokenSource = fs.readFileSync(tokenPath, "utf8");
const tokens = Object.fromEntries(
  [...tokenSource.matchAll(/^\s*(--[\w-]+):\s*([^;]+);/gm)].map((match) => [
    match[1],
    match[2].trim(),
  ]),
);
const assets = Object.fromEntries(
  Object.entries(assetPaths).map(([name, assetPath]) => [
    name,
    {
      fileName: path.basename(assetPath),
      mimeType: "image/png",
      base64: fs.readFileSync(assetPath).toString("base64"),
    },
  ]),
);
const vectors = Object.fromEntries(
  Object.entries(vectorPaths).map(([name, vectorPath]) => [
    name,
    fs.readFileSync(vectorPath, "utf8"),
  ]),
);

const requiredTokens = [
  "--color-canvas",
  "--color-surface",
  "--color-surface-strong",
  "--color-ink",
  "--color-ink-muted",
  "--color-green-deep",
  "--color-green",
  "--color-green-soft",
  "--color-green-tint",
  "--color-burgundy",
  "--color-burgundy-tint",
  "--color-border",
];

for (const token of requiredTokens) {
  if (!tokens[token]?.startsWith("#")) {
    throw new Error(`Missing literal production token ${token} in src/styles/tokens.css.`);
  }
}

let commit = "working-tree";
try {
  commit = execFileSync("git", ["rev-parse", "--short", "HEAD"], {
    cwd: repositoryRoot,
    encoding: "utf8",
  }).trim();
  const workingTree = execFileSync(
    "git",
    ["status", "--porcelain", "--untracked-files=normal"],
    { cwd: repositoryRoot, encoding: "utf8" },
  ).trim();
  if (workingTree) commit = `${commit}+working-tree`;
} catch {
  // A packaged development build can still be validated outside Git.
}

const packagedRelease = {
  ...release,
  commit,
  packagedAt: new Date().toISOString(),
};
const header = [
  "/* Generated by package.mjs. Do not edit this file directly. */",
  `const ABI_DESIGN_RELEASE = Object.freeze(${JSON.stringify(packagedRelease)});`,
  `const ABI_DESIGN_TOKENS = Object.freeze(${JSON.stringify(tokens)});`,
  `const ABI_DESIGN_ASSETS = Object.freeze(${JSON.stringify(assets)});`,
  `const ABI_DESIGN_VECTORS = Object.freeze(${JSON.stringify(vectors)});`,
  "",
].join("\n");

fs.mkdirSync(outputDirectory, { recursive: true });
fs.writeFileSync(outputPath, `${header}${source}`, "utf8");

console.log(
  `Packaged Abi Figma design release ${release.version} from ${commit} (${requiredTokens.length} production tokens, ${Object.keys(assets).length} production images, ${Object.keys(vectors).length} production vectors).`,
);
